from sqlalchemy import DateTime, Text, Column, Integer, Float

from database import Base

class Novel_data(Base):
    __tablename__ = "novel_data"
    
    id = Column(Integer, primary_key=True, index=True)
    title = Column(Text)
    ncode = Column(Text)
    userid = Column(Integer)
    writer = Column(Text)
    story = Column(Text)
    biggenre = Column(Integer)
    genre = Column(Integer)
    keyword = Column(Text)
    general_firstup = Column(Text)
    general_lastup = Column(Text)
    novel_type = Column(Integer)
    end = Column(Integer)
    general_all_no = Column(Integer)
    length = Column(Integer)
    time = Column(Integer)
    isstop = Column(Integer)
    isr15 = Column(Integer)
    isbl = Column(Integer)
    isgl = Column(Integer)
    iszankoku = Column(Integer)
    istensei = Column(Integer)
    istenni = Column(Integer)
    pc_or_k = Column(Integer)
    global_point = Column(Integer)
    daily_point = Column(Integer)
    weekly_point = Column(Integer)
    monthly_point = Column(Integer)
    quarter_point = Column(Integer)
    yearly_point = Column(Integer)
    fav_novel_cnt = Column(Integer)
    impression_cnt = Column(Integer)
    review_cnt = Column(Integer)
    all_point = Column(Integer)
    all_hyoka_cnt = Column(Integer)
    sasie_cnt = Column(Integer)
    kaiwaritu = Column(Integer)
    novelupdated_at = Column(DateTime)
    updated_at = Column(DateTime)